// ---
// relationships:
//   implements: usage-decoder
// ---
// Generated by scripts/generate-decoder-revision.mjs.
export const decoderRevision = "c580d62a4c36b92e9457a60ba0e41f1ffa6cb0ceae8e4b59259cb88207c30275";
