// ---
// relationships:
//   implements: usage-decoder
// ---
// Generated by scripts/generate-decoder-revision.mjs.
export const decoderRevision = "453a6e4b48e80808b0956b8b74cccb31601eba096cc96339bed3fa3375dbeea6";
