// ---
// relationships:
//   implements: host-cli-comparator-lint
// ---
// Generated by scripts/generate-comparator-library.mjs.
import type { ComparatorLintLibrary } from "./index.ts";
// @ts-expect-error Bun imports declaration files as text; TypeScript treats them as declarations.
import contract from "@wyrd-company/manifold-shared/comparator.d.ts" with { type: "text" };
// @ts-expect-error Bun imports declaration files as text; TypeScript treats them as declarations.
import lib0 from "typescript/lib/lib.decorators.d.ts" with { type: "text" };
// @ts-expect-error Bun imports declaration files as text; TypeScript treats them as declarations.
import lib1 from "typescript/lib/lib.decorators.legacy.d.ts" with { type: "text" };
// @ts-expect-error Bun imports declaration files as text; TypeScript treats them as declarations.
import lib2 from "typescript/lib/lib.es2015.collection.d.ts" with { type: "text" };
// @ts-expect-error Bun imports declaration files as text; TypeScript treats them as declarations.
import lib3 from "typescript/lib/lib.es2015.core.d.ts" with { type: "text" };
// @ts-expect-error Bun imports declaration files as text; TypeScript treats them as declarations.
import lib4 from "typescript/lib/lib.es2015.d.ts" with { type: "text" };
// @ts-expect-error Bun imports declaration files as text; TypeScript treats them as declarations.
import lib5 from "typescript/lib/lib.es2015.generator.d.ts" with { type: "text" };
// @ts-expect-error Bun imports declaration files as text; TypeScript treats them as declarations.
import lib6 from "typescript/lib/lib.es2015.iterable.d.ts" with { type: "text" };
// @ts-expect-error Bun imports declaration files as text; TypeScript treats them as declarations.
import lib7 from "typescript/lib/lib.es2015.promise.d.ts" with { type: "text" };
// @ts-expect-error Bun imports declaration files as text; TypeScript treats them as declarations.
import lib8 from "typescript/lib/lib.es2015.proxy.d.ts" with { type: "text" };
// @ts-expect-error Bun imports declaration files as text; TypeScript treats them as declarations.
import lib9 from "typescript/lib/lib.es2015.reflect.d.ts" with { type: "text" };
// @ts-expect-error Bun imports declaration files as text; TypeScript treats them as declarations.
import lib10 from "typescript/lib/lib.es2015.symbol.d.ts" with { type: "text" };
// @ts-expect-error Bun imports declaration files as text; TypeScript treats them as declarations.
import lib11 from "typescript/lib/lib.es2015.symbol.wellknown.d.ts" with { type: "text" };
// @ts-expect-error Bun imports declaration files as text; TypeScript treats them as declarations.
import lib12 from "typescript/lib/lib.es2016.array.include.d.ts" with { type: "text" };
// @ts-expect-error Bun imports declaration files as text; TypeScript treats them as declarations.
import lib13 from "typescript/lib/lib.es2016.d.ts" with { type: "text" };
// @ts-expect-error Bun imports declaration files as text; TypeScript treats them as declarations.
import lib14 from "typescript/lib/lib.es2016.intl.d.ts" with { type: "text" };
// @ts-expect-error Bun imports declaration files as text; TypeScript treats them as declarations.
import lib15 from "typescript/lib/lib.es2017.arraybuffer.d.ts" with { type: "text" };
// @ts-expect-error Bun imports declaration files as text; TypeScript treats them as declarations.
import lib16 from "typescript/lib/lib.es2017.d.ts" with { type: "text" };
// @ts-expect-error Bun imports declaration files as text; TypeScript treats them as declarations.
import lib17 from "typescript/lib/lib.es2017.date.d.ts" with { type: "text" };
// @ts-expect-error Bun imports declaration files as text; TypeScript treats them as declarations.
import lib18 from "typescript/lib/lib.es2017.intl.d.ts" with { type: "text" };
// @ts-expect-error Bun imports declaration files as text; TypeScript treats them as declarations.
import lib19 from "typescript/lib/lib.es2017.object.d.ts" with { type: "text" };
// @ts-expect-error Bun imports declaration files as text; TypeScript treats them as declarations.
import lib20 from "typescript/lib/lib.es2017.sharedmemory.d.ts" with { type: "text" };
// @ts-expect-error Bun imports declaration files as text; TypeScript treats them as declarations.
import lib21 from "typescript/lib/lib.es2017.string.d.ts" with { type: "text" };
// @ts-expect-error Bun imports declaration files as text; TypeScript treats them as declarations.
import lib22 from "typescript/lib/lib.es2017.typedarrays.d.ts" with { type: "text" };
// @ts-expect-error Bun imports declaration files as text; TypeScript treats them as declarations.
import lib23 from "typescript/lib/lib.es2018.asyncgenerator.d.ts" with { type: "text" };
// @ts-expect-error Bun imports declaration files as text; TypeScript treats them as declarations.
import lib24 from "typescript/lib/lib.es2018.asynciterable.d.ts" with { type: "text" };
// @ts-expect-error Bun imports declaration files as text; TypeScript treats them as declarations.
import lib25 from "typescript/lib/lib.es2018.d.ts" with { type: "text" };
// @ts-expect-error Bun imports declaration files as text; TypeScript treats them as declarations.
import lib26 from "typescript/lib/lib.es2018.intl.d.ts" with { type: "text" };
// @ts-expect-error Bun imports declaration files as text; TypeScript treats them as declarations.
import lib27 from "typescript/lib/lib.es2018.promise.d.ts" with { type: "text" };
// @ts-expect-error Bun imports declaration files as text; TypeScript treats them as declarations.
import lib28 from "typescript/lib/lib.es2018.regexp.d.ts" with { type: "text" };
// @ts-expect-error Bun imports declaration files as text; TypeScript treats them as declarations.
import lib29 from "typescript/lib/lib.es2019.array.d.ts" with { type: "text" };
// @ts-expect-error Bun imports declaration files as text; TypeScript treats them as declarations.
import lib30 from "typescript/lib/lib.es2019.d.ts" with { type: "text" };
// @ts-expect-error Bun imports declaration files as text; TypeScript treats them as declarations.
import lib31 from "typescript/lib/lib.es2019.intl.d.ts" with { type: "text" };
// @ts-expect-error Bun imports declaration files as text; TypeScript treats them as declarations.
import lib32 from "typescript/lib/lib.es2019.object.d.ts" with { type: "text" };
// @ts-expect-error Bun imports declaration files as text; TypeScript treats them as declarations.
import lib33 from "typescript/lib/lib.es2019.string.d.ts" with { type: "text" };
// @ts-expect-error Bun imports declaration files as text; TypeScript treats them as declarations.
import lib34 from "typescript/lib/lib.es2019.symbol.d.ts" with { type: "text" };
// @ts-expect-error Bun imports declaration files as text; TypeScript treats them as declarations.
import lib35 from "typescript/lib/lib.es2020.bigint.d.ts" with { type: "text" };
// @ts-expect-error Bun imports declaration files as text; TypeScript treats them as declarations.
import lib36 from "typescript/lib/lib.es2020.d.ts" with { type: "text" };
// @ts-expect-error Bun imports declaration files as text; TypeScript treats them as declarations.
import lib37 from "typescript/lib/lib.es2020.date.d.ts" with { type: "text" };
// @ts-expect-error Bun imports declaration files as text; TypeScript treats them as declarations.
import lib38 from "typescript/lib/lib.es2020.intl.d.ts" with { type: "text" };
// @ts-expect-error Bun imports declaration files as text; TypeScript treats them as declarations.
import lib39 from "typescript/lib/lib.es2020.number.d.ts" with { type: "text" };
// @ts-expect-error Bun imports declaration files as text; TypeScript treats them as declarations.
import lib40 from "typescript/lib/lib.es2020.promise.d.ts" with { type: "text" };
// @ts-expect-error Bun imports declaration files as text; TypeScript treats them as declarations.
import lib41 from "typescript/lib/lib.es2020.sharedmemory.d.ts" with { type: "text" };
// @ts-expect-error Bun imports declaration files as text; TypeScript treats them as declarations.
import lib42 from "typescript/lib/lib.es2020.string.d.ts" with { type: "text" };
// @ts-expect-error Bun imports declaration files as text; TypeScript treats them as declarations.
import lib43 from "typescript/lib/lib.es2020.symbol.wellknown.d.ts" with { type: "text" };
// @ts-expect-error Bun imports declaration files as text; TypeScript treats them as declarations.
import lib44 from "typescript/lib/lib.es2021.d.ts" with { type: "text" };
// @ts-expect-error Bun imports declaration files as text; TypeScript treats them as declarations.
import lib45 from "typescript/lib/lib.es2021.intl.d.ts" with { type: "text" };
// @ts-expect-error Bun imports declaration files as text; TypeScript treats them as declarations.
import lib46 from "typescript/lib/lib.es2021.promise.d.ts" with { type: "text" };
// @ts-expect-error Bun imports declaration files as text; TypeScript treats them as declarations.
import lib47 from "typescript/lib/lib.es2021.string.d.ts" with { type: "text" };
// @ts-expect-error Bun imports declaration files as text; TypeScript treats them as declarations.
import lib48 from "typescript/lib/lib.es2021.weakref.d.ts" with { type: "text" };
// @ts-expect-error Bun imports declaration files as text; TypeScript treats them as declarations.
import lib49 from "typescript/lib/lib.es2022.array.d.ts" with { type: "text" };
// @ts-expect-error Bun imports declaration files as text; TypeScript treats them as declarations.
import lib50 from "typescript/lib/lib.es2022.d.ts" with { type: "text" };
// @ts-expect-error Bun imports declaration files as text; TypeScript treats them as declarations.
import lib51 from "typescript/lib/lib.es2022.error.d.ts" with { type: "text" };
// @ts-expect-error Bun imports declaration files as text; TypeScript treats them as declarations.
import lib52 from "typescript/lib/lib.es2022.intl.d.ts" with { type: "text" };
// @ts-expect-error Bun imports declaration files as text; TypeScript treats them as declarations.
import lib53 from "typescript/lib/lib.es2022.object.d.ts" with { type: "text" };
// @ts-expect-error Bun imports declaration files as text; TypeScript treats them as declarations.
import lib54 from "typescript/lib/lib.es2022.regexp.d.ts" with { type: "text" };
// @ts-expect-error Bun imports declaration files as text; TypeScript treats them as declarations.
import lib55 from "typescript/lib/lib.es2022.string.d.ts" with { type: "text" };
// @ts-expect-error Bun imports declaration files as text; TypeScript treats them as declarations.
import lib56 from "typescript/lib/lib.es5.d.ts" with { type: "text" };
export const comparatorLintLibrary: ComparatorLintLibrary = {
  contract,
  libFiles: new Map([
    ["lib.decorators.d.ts", lib0],
    ["lib.decorators.legacy.d.ts", lib1],
    ["lib.es2015.collection.d.ts", lib2],
    ["lib.es2015.core.d.ts", lib3],
    ["lib.es2015.d.ts", lib4],
    ["lib.es2015.generator.d.ts", lib5],
    ["lib.es2015.iterable.d.ts", lib6],
    ["lib.es2015.promise.d.ts", lib7],
    ["lib.es2015.proxy.d.ts", lib8],
    ["lib.es2015.reflect.d.ts", lib9],
    ["lib.es2015.symbol.d.ts", lib10],
    ["lib.es2015.symbol.wellknown.d.ts", lib11],
    ["lib.es2016.array.include.d.ts", lib12],
    ["lib.es2016.d.ts", lib13],
    ["lib.es2016.intl.d.ts", lib14],
    ["lib.es2017.arraybuffer.d.ts", lib15],
    ["lib.es2017.d.ts", lib16],
    ["lib.es2017.date.d.ts", lib17],
    ["lib.es2017.intl.d.ts", lib18],
    ["lib.es2017.object.d.ts", lib19],
    ["lib.es2017.sharedmemory.d.ts", lib20],
    ["lib.es2017.string.d.ts", lib21],
    ["lib.es2017.typedarrays.d.ts", lib22],
    ["lib.es2018.asyncgenerator.d.ts", lib23],
    ["lib.es2018.asynciterable.d.ts", lib24],
    ["lib.es2018.d.ts", lib25],
    ["lib.es2018.intl.d.ts", lib26],
    ["lib.es2018.promise.d.ts", lib27],
    ["lib.es2018.regexp.d.ts", lib28],
    ["lib.es2019.array.d.ts", lib29],
    ["lib.es2019.d.ts", lib30],
    ["lib.es2019.intl.d.ts", lib31],
    ["lib.es2019.object.d.ts", lib32],
    ["lib.es2019.string.d.ts", lib33],
    ["lib.es2019.symbol.d.ts", lib34],
    ["lib.es2020.bigint.d.ts", lib35],
    ["lib.es2020.d.ts", lib36],
    ["lib.es2020.date.d.ts", lib37],
    ["lib.es2020.intl.d.ts", lib38],
    ["lib.es2020.number.d.ts", lib39],
    ["lib.es2020.promise.d.ts", lib40],
    ["lib.es2020.sharedmemory.d.ts", lib41],
    ["lib.es2020.string.d.ts", lib42],
    ["lib.es2020.symbol.wellknown.d.ts", lib43],
    ["lib.es2021.d.ts", lib44],
    ["lib.es2021.intl.d.ts", lib45],
    ["lib.es2021.promise.d.ts", lib46],
    ["lib.es2021.string.d.ts", lib47],
    ["lib.es2021.weakref.d.ts", lib48],
    ["lib.es2022.array.d.ts", lib49],
    ["lib.es2022.d.ts", lib50],
    ["lib.es2022.error.d.ts", lib51],
    ["lib.es2022.intl.d.ts", lib52],
    ["lib.es2022.object.d.ts", lib53],
    ["lib.es2022.regexp.d.ts", lib54],
    ["lib.es2022.string.d.ts", lib55],
    ["lib.es5.d.ts", lib56],
  ]),
};
