// ---
// relationships:
//   implements: host-command-catalog
// ---
// Generated by scripts/generate-command-tree.mjs.
export const commandTree = {
  tool: {
    name: "manifold-host",
    summary: "The Manifold host CLI, installed on each environment.",
  },
  help: {
    flags: ["-h", "--help"],
    description: "Show help for the command and exit.",
  },
  commands: [
    {
      name: "blueprint",
      summary: "Work with blueprints in a process repository.",
      arguments: [],
      flags: [],
      exitCodes: [],
      examples: [],
      subcommands: [
        {
          name: "lint",
          summary: "Lint blueprint files with the rules the service runs when it loads them.",
          arguments: [
            {
              name: "files",
              description:
                "Paths to blueprint files. Optional with `--repository`, which then lints every blueprint the repository runs, bundled blueprints included.",
              position: 0,
              required: false,
              greedy: true,
            },
          ],
          flags: [
            {
              flags: ["--configuration-bound"],
              kind: "option",
              description:
                "The token lint's configuration bound: the configurations a blueprint's graph may hold before each gate's verdict is `unknown`. An integer of at least 1.",
              required: false,
              default: 20000,
              value: {
                type: "integer",
              },
            },
            {
              flags: ["--repository"],
              kind: "option",
              description:
                "The process repository checkout whose `task-metadata.yml` and `bindings.yml` give the declared lifecycle options a literal `status` of a `github-card-move` invoke is checked against. With no file argument, every blueprint the repository runs is linted, bundled blueprints included. Without it, `status` is not checked.",
              required: false,
              value: {
                type: "path",
              },
            },
          ],
          exitCodes: [
            {
              code: 0,
              meaning: "No file has a finding; files may have warnings.",
            },
            {
              code: 1,
              meaning: "At least one file has a finding.",
            },
            {
              code: 2,
              meaning:
                "No file was given without `--repository`, a file could not be read, `--configuration-bound` is not an integer of at least 1, or the task metadata declaration of `--repository` has a finding.",
            },
          ],
          examples: [
            "manifold-host blueprint lint blueprints/delivery.yml",
            "manifold-host blueprint lint blueprints/delivery.yml blueprints/returns.yml",
            "manifold-host blueprint lint --configuration-bound 50000 blueprints/delivery.yml",
            "manifold-host blueprint lint --repository . blueprints/delivery.yml",
            "manifold-host blueprint lint --repository .",
          ],
        },
      ],
    },
    {
      name: "comparator",
      summary: "Work with gate comparators in a process repository.",
      arguments: [],
      flags: [],
      exitCodes: [],
      examples: [],
      subcommands: [
        {
          name: "lint",
          summary: "Typecheck comparators against the comparator contract without running them.",
          arguments: [
            {
              name: "files",
              description: "Paths to comparator TypeScript source files.",
              position: 0,
              required: true,
              greedy: true,
            },
          ],
          flags: [],
          exitCodes: [
            {
              code: 0,
              meaning: "Every file is clean.",
            },
            {
              code: 1,
              meaning: "At least one file has a diagnostic.",
            },
            {
              code: 2,
              meaning: "No file was given, or a file could not be read.",
            },
          ],
          examples: [
            "manifold-host comparator lint comparators/ordered.ts",
            "manifold-host comparator lint comparators/ordered.ts comparators/drawn.ts",
          ],
        },
      ],
    },
    {
      name: "expressions",
      summary: "Work with blueprint expressions in a process repository.",
      arguments: [],
      flags: [],
      exitCodes: [],
      examples: [],
      subcommands: [
        {
          name: "lint",
          summary: "Lint the JSONata guards, matches, assignments, and mappings of blueprints.",
          arguments: [
            {
              name: "files",
              description: "Paths to YAML documents with `machine` and `schemas`.",
              position: 0,
              required: true,
              greedy: true,
            },
          ],
          flags: [],
          exitCodes: [
            {
              code: 0,
              meaning: "Every file is clean.",
            },
            {
              code: 1,
              meaning: "At least one file has a finding.",
            },
            {
              code: 2,
              meaning: "No file was given, or a file could not be read or is not a blueprint.",
            },
          ],
          examples: ["manifold-host expressions lint blueprints/review.yml"],
        },
      ],
    },
    {
      name: "help",
      summary: "Show help for the host CLI or for a command.",
      arguments: [
        {
          name: "command",
          description:
            "The path of a command or group, such as `usage push`, read from the root one name at a time. Without it, the help of the host CLI is shown. No command runs.",
          position: 0,
          required: false,
          greedy: true,
        },
      ],
      flags: [],
      exitCodes: [
        {
          code: 0,
          meaning: "The help was shown.",
        },
        {
          code: 2,
          meaning:
            "A name of the path is not a subcommand of the command before it, or a flag other than `-h` or `--help` is given. The usage of the command reached is on standard error.",
        },
      ],
      examples: ["manifold-host help", "manifold-host help usage push"],
    },
    {
      name: "manifest",
      summary: "Work with the manifest of a process repository.",
      arguments: [],
      flags: [],
      exitCodes: [],
      examples: [],
      subcommands: [
        {
          name: "lint",
          summary:
            "Lint `manifold.yml` and the decision models it reaches in a process repository checkout.",
          arguments: [
            {
              name: "repository",
              description:
                "The process repository checkout directory. Defaults to the current directory.",
              position: 0,
              required: false,
            },
          ],
          flags: [],
          exitCodes: [
            {
              code: 0,
              meaning: "There is no error finding.",
            },
            {
              code: 1,
              meaning: "At least one error finding.",
            },
            {
              code: 2,
              meaning: "The directory or a file could not be read.",
            },
          ],
          examples: ["manifold-host manifest lint", "manifold-host manifest lint ./process"],
        },
      ],
    },
    {
      name: "mcp",
      summary: "Serve the agent tools to a provider harness over MCP on standard input and output.",
      arguments: [],
      flags: [
        {
          flags: ["--service"],
          kind: "option",
          description: "The base URL of the Manifold service, `http` or `https`.",
          required: true,
          repeatable: false,
          value: {
            type: "string",
          },
        },
        {
          flags: ["--environment"],
          kind: "option",
          description:
            "The name of this environment, as the service configuration's `environments` section names it.",
          required: true,
          repeatable: false,
          value: {
            type: "string",
          },
        },
        {
          flags: ["--request-timeout-ms"],
          kind: "option",
          description:
            "The most time in milliseconds the plugin waits for the service's response to one tool call. Default 30000; from 1000 to 300000.",
          required: false,
          repeatable: false,
          value: {
            type: "integer",
          },
        },
      ],
      exitCodes: [
        {
          code: 0,
          meaning: "Standard input closed and the server stopped.",
        },
        {
          code: 2,
          meaning:
            "The command line is invalid: an unknown option, a missing `--service` or `--environment`, a service URL that is not `http` or `https`, an environment name that is not a declared name, or a request timeout out of range. Nothing is served.",
        },
      ],
      examples: ["manifold-host mcp --service http://127.0.0.1:8080 --environment workstation"],
    },
    {
      name: "portfolio",
      summary: "Work with the portfolio and bindings of a process repository.",
      arguments: [],
      flags: [],
      exitCodes: [],
      examples: [],
      subcommands: [
        {
          name: "lint",
          summary:
            "Lint `portfolio.yml` and `bindings.yml` in a process repository checkout, and the accounts `portfolio.yml` allocates against `accounts.yml`.",
          arguments: [
            {
              name: "repository",
              description:
                "The process repository checkout directory. Defaults to the current directory.",
              position: 0,
              required: false,
            },
          ],
          flags: [],
          exitCodes: [
            {
              code: 0,
              meaning: "There is no finding; there may be warnings.",
            },
            {
              code: 1,
              meaning: "At least one file has a finding.",
            },
            {
              code: 2,
              meaning: "The directory or a file could not be read.",
            },
          ],
          examples: ["manifold-host portfolio lint", "manifold-host portfolio lint ./process"],
        },
      ],
    },
    {
      name: "task-metadata",
      summary: "Work with the task metadata declaration of a process repository.",
      arguments: [],
      flags: [],
      exitCodes: [],
      examples: [],
      subcommands: [
        {
          name: "lint",
          summary:
            "Lint `task-metadata.yml` against `bindings.yml` in a process repository checkout.",
          arguments: [
            {
              name: "repository",
              description:
                "The process repository checkout directory. Defaults to the current directory.",
              position: 0,
              required: false,
            },
          ],
          flags: [],
          exitCodes: [
            {
              code: 0,
              meaning: "There is no finding.",
            },
            {
              code: 1,
              meaning: "The declaration has at least one finding.",
            },
            {
              code: 2,
              meaning: "The directory or a file could not be read.",
            },
          ],
          examples: [
            "manifold-host task-metadata lint",
            "manifold-host task-metadata lint ./process",
          ],
        },
      ],
    },
    {
      name: "usage",
      summary: "Read provider usage on this environment.",
      arguments: [],
      flags: [],
      exitCodes: [],
      examples: [],
      subcommands: [
        {
          name: "decode",
          summary: "Decode provider session files into usage records on standard output.",
          arguments: [],
          flags: [
            {
              flags: ["--root"],
              kind: "option",
              description:
                "A provider and the directory where it keeps its sessions, written `<provider>=<path>`. The provider is one of `claude`, `codex`, `cursor`, `grok`, and `opencode`. Repeatable; roots decode in the order given. When absent, every provider's default root decodes.",
              required: false,
              repeatable: true,
              value: {
                type: "string",
              },
            },
          ],
          exitCodes: [
            {
              code: 0,
              meaning: "Every root decoded. Source errors, if any, are records on standard output.",
            },
            {
              code: 1,
              meaning:
                "The decode ended before every root decoded. Standard output holds the records written before the failure, and standard error names the failure.",
            },
            {
              code: 2,
              meaning:
                "The command line is invalid: an unknown option, a `--root` without `=`, an unknown provider, or an empty path. Nothing is decoded.",
            },
          ],
          examples: [
            "manifold-host usage decode",
            "manifold-host usage decode --root codex=/srv/agents/codex-home --root claude=/home/example/.claude",
          ],
        },
        {
          name: "lint",
          summary:
            "Lint `accounts.yml` and `prices.yml` in a process repository checkout, and the accounts `portfolio.yml` allocates against `accounts.yml`.",
          arguments: [
            {
              name: "repository",
              description:
                "The process repository checkout directory. Defaults to the current directory.",
              position: 0,
              required: false,
            },
          ],
          flags: [],
          exitCodes: [
            {
              code: 0,
              meaning: "There is no finding; there may be warnings.",
            },
            {
              code: 1,
              meaning: "At least one file has a finding.",
            },
            {
              code: 2,
              meaning: "The directory or a file could not be read.",
            },
          ],
          examples: ["manifold-host usage lint", "manifold-host usage lint ./process"],
        },
        {
          name: "push",
          summary: "Decode provider session files and push the usage records to the service.",
          arguments: [],
          flags: [
            {
              flags: ["--service"],
              kind: "option",
              description: "The base URL of the Manifold service, `http` or `https`.",
              required: true,
              repeatable: false,
              value: {
                type: "string",
              },
            },
            {
              flags: ["--environment"],
              kind: "option",
              description:
                "The name of this environment, as the service configuration's `environments` section names it.",
              required: true,
              repeatable: false,
              value: {
                type: "string",
              },
            },
            {
              flags: ["--root"],
              kind: "option",
              description:
                "A provider and the directory where it keeps its sessions, as for `usage decode`. When absent, every provider's default root decodes.",
              required: false,
              repeatable: true,
              value: {
                type: "string",
              },
            },
            {
              flags: ["--t3-home"],
              kind: "option",
              description:
                "T3 Code's data directory, whose `userdata/state.sqlite` holds each thread's provider session. When absent, `T3CODE_HOME`, else `~/.t3`.",
              required: false,
              repeatable: false,
              value: {
                type: "string",
              },
            },
            {
              flags: ["--state-dir"],
              kind: "option",
              description:
                "The directory of the host CLI's state. When absent, `XDG_STATE_HOME/manifold-host`, else `~/.local/state/manifold-host`.",
              required: false,
              repeatable: false,
              value: {
                type: "string",
              },
            },
          ],
          exitCodes: [
            {
              code: 0,
              meaning: "Every mapping request and every batch was acknowledged by the service.",
            },
            {
              code: 1,
              meaning:
                "The run ended before every mapping request and batch was acknowledged: a request did not answer 200, the connection failed, or T3 Code's database could not be read. The push state holds the mappings and batches acknowledged before the failure, and standard error names it.",
            },
            {
              code: 2,
              meaning: "The command line is invalid. Nothing is decoded or sent.",
            },
          ],
          examples: [
            "manifold-host usage push --service http://127.0.0.1:8080 --environment env-one",
          ],
        },
      ],
    },
  ],
} as const;
export type RunnablePath =
  | "blueprint lint"
  | "comparator lint"
  | "expressions lint"
  | "help"
  | "manifest lint"
  | "mcp"
  | "portfolio lint"
  | "task-metadata lint"
  | "usage decode"
  | "usage lint"
  | "usage push";
