// ---
// relationships:
//   implements: [usage-push, usage-record, accounts-declaration, price-table]
// ---
// Generated by scripts/generate-usage-schemas.mjs.
/* oxlint-disable unicorn/no-thenable -- JSON Schema conditionals use then. */
export const usagePushSchema = {
  $schema: "https://json-schema.org/draft/2020-12/schema",
  $id: "https://manifold.wyrd.company/schemas/usage-push",
  title: "Usage push request",
  description:
    "The body of `POST /api/usage/push`: usage records from one environment and the T3 Code thread of each provider session they name.",
  type: "object",
  additionalProperties: false,
  required: ["environment", "threads", "records"],
  properties: {
    environment: {
      description: "The environment the host runs on, as service configuration names it.",
      $ref: "https://manifold.wyrd.company/schemas/service-configuration#/$defs/declared-name",
    },
    threads: {
      type: "array",
      maxItems: 1000,
      items: {
        $ref: "#/$defs/mapping",
      },
    },
    records: {
      type: "array",
      maxItems: 1000,
      items: {
        $ref: "https://manifold.wyrd.company/schemas/usage-record",
      },
    },
  },
  $defs: {
    mapping: {
      description: "The T3 Code thread that runs one provider session.",
      type: "object",
      additionalProperties: false,
      required: ["provider", "providerSessionId", "threadId"],
      properties: {
        provider: {
          $ref: "https://manifold.wyrd.company/schemas/usage-record#/$defs/provider",
        },
        providerSessionId: {
          type: "string",
          minLength: 1,
        },
        threadId: {
          type: "string",
          minLength: 1,
        },
        providerInstance: {
          description: "The T3 Code provider instance that runs the session.",
          type: "string",
          minLength: 1,
        },
      },
    },
    count: {
      type: "integer",
      minimum: 0,
    },
    response: {
      description: "The body of a 200 answer.",
      type: "object",
      additionalProperties: false,
      required: ["calls", "threads", "sourceErrors"],
      properties: {
        calls: {
          type: "object",
          additionalProperties: false,
          required: ["accepted", "pending", "replayed"],
          properties: {
            accepted: {
              $ref: "#/$defs/count",
            },
            pending: {
              $ref: "#/$defs/count",
            },
            replayed: {
              $ref: "#/$defs/count",
            },
          },
        },
        threads: {
          type: "object",
          additionalProperties: false,
          required: ["accepted", "replayed", "conflicting"],
          properties: {
            accepted: {
              $ref: "#/$defs/count",
            },
            replayed: {
              $ref: "#/$defs/count",
            },
            conflicting: {
              $ref: "#/$defs/count",
            },
          },
        },
        sourceErrors: {
          $ref: "#/$defs/count",
        },
      },
    },
    error: {
      description: "The body of every answer other than 200 that the module writes.",
      type: "object",
      required: ["error", "message"],
      properties: {
        error: {
          type: "string",
          enum: [
            "invalid-request",
            "too-large",
            "unsupported-media-type",
            "unknown-environment",
            "internal",
          ],
        },
        message: {
          type: "string",
        },
        issues: {
          type: "array",
          items: {
            type: "object",
            required: ["pointer", "message"],
            properties: {
              pointer: {
                type: "string",
              },
              message: {
                type: "string",
              },
            },
          },
        },
      },
    },
  },
};

export const usageRecordSchema = {
  $schema: "https://json-schema.org/draft/2020-12/schema",
  $id: "https://manifold.wyrd.company/schemas/usage-record",
  title: "Usage record",
  description:
    "One line of `manifold-host usage decode` output: a call decoded from a provider session file, or an error with one source.",
  oneOf: [
    {
      $ref: "#/$defs/call",
    },
    {
      $ref: "#/$defs/sourceError",
    },
  ],
  $defs: {
    provider: {
      type: "string",
      enum: ["claude", "codex", "cursor", "grok", "opencode"],
    },
    count: {
      type: "integer",
      minimum: 0,
    },
    call: {
      type: "object",
      additionalProperties: false,
      required: [
        "type",
        "key",
        "provider",
        "providerSessionId",
        "unit",
        "timestamp",
        "model",
        "tokens",
        "speed",
        "granularity",
        "estimated",
      ],
      properties: {
        type: {
          const: "call",
        },
        key: {
          type: "string",
          minLength: 1,
        },
        provider: {
          $ref: "#/$defs/provider",
        },
        providerSessionId: {
          type: "string",
          minLength: 1,
        },
        unit: {
          $ref: "#/$defs/unit",
        },
        timestamp: {
          type: "string",
          pattern: "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\.\\d{3}Z$",
        },
        model: {
          type: ["string", "null"],
          minLength: 1,
        },
        tokens: {
          type: "object",
          additionalProperties: false,
          required: [
            "input",
            "output",
            "cacheRead",
            "cacheWrite",
            "cacheWriteOneHour",
            "reasoning",
            "webSearchRequests",
          ],
          properties: {
            input: {
              $ref: "#/$defs/count",
            },
            output: {
              $ref: "#/$defs/count",
            },
            cacheRead: {
              $ref: "#/$defs/count",
            },
            cacheWrite: {
              $ref: "#/$defs/count",
            },
            cacheWriteOneHour: {
              $ref: "#/$defs/count",
            },
            reasoning: {
              $ref: "#/$defs/count",
            },
            webSearchRequests: {
              $ref: "#/$defs/count",
            },
          },
        },
        speed: {
          type: "string",
          enum: ["standard", "fast"],
        },
        granularity: {
          type: "string",
          enum: ["call", "session-total"],
        },
        estimated: {
          type: "boolean",
        },
      },
    },
    unit: {
      type: "object",
      additionalProperties: false,
      required: ["id", "kind"],
      properties: {
        id: {
          type: "string",
          minLength: 1,
        },
        kind: {
          type: "string",
          enum: ["session", "subagent", "child-thread"],
        },
        parentId: {
          type: "string",
          minLength: 1,
        },
        name: {
          type: "string",
        },
        role: {
          type: "string",
        },
      },
      if: {
        properties: {
          kind: {
            const: "session",
          },
        },
      },
      then: {
        properties: {
          parentId: false,
        },
      },
    },
    sourceError: {
      type: "object",
      additionalProperties: false,
      required: ["type", "provider", "source", "code", "records"],
      properties: {
        type: {
          const: "source-error",
        },
        provider: {
          $ref: "#/$defs/provider",
        },
        source: {
          type: "string",
          minLength: 1,
        },
        code: {
          type: "string",
          enum: ["unreadable", "truncated", "malformed-record", "unknown-record", "decoder-failed"],
        },
        records: {
          $ref: "#/$defs/count",
        },
        firstRecord: {
          $ref: "#/$defs/count",
        },
        detail: {
          type: "string",
          maxLength: 200,
          pattern: "^[^/\\\\]*$",
        },
      },
    },
  },
};

export const accountsDeclarationSchema = {
  $schema: "https://json-schema.org/draft/2020-12/schema",
  $id: "https://manifold.wyrd.company/schemas/accounts-declaration",
  title: "Accounts declaration",
  description:
    "The document in `accounts.yml` at the root of the process repository: the accounts usage is charged to. An empty document declares no accounts.",
  type: "object",
  additionalProperties: false,
  properties: {
    accounts: {
      description: "Accounts, keyed by account name, a declared name.",
      type: "object",
      propertyNames: {
        $ref: "https://manifold.wyrd.company/schemas/service-configuration#/$defs/declared-name",
      },
      additionalProperties: {
        $ref: "#/$defs/account",
      },
    },
  },
  $defs: {
    account: {
      type: "object",
      additionalProperties: false,
      required: ["unit", "kind", "capacity"],
      properties: {
        unit: {
          description: "The account's native unit.",
          type: "string",
          enum: ["usd"],
        },
        kind: {
          description:
            "`api` for an account billed by usage against a budget; `subscription` for an account with a usage limit that resets.",
          type: "string",
          enum: ["api", "subscription"],
        },
        capacity: {
          $ref: "#/$defs/capacity",
        },
        usage: {
          description: "The usage that charges the account.",
          type: "array",
          items: {
            $ref: "#/$defs/usage",
          },
        },
      },
    },
    capacity: {
      description: "What the account can spend in each window, and when its windows open.",
      type: "object",
      additionalProperties: false,
      required: ["amount", "reset", "every"],
      properties: {
        amount: {
          description:
            "The capacity of one window in the account's unit: a positive decimal with at most six fractional digits.",
          type: "number",
          exclusiveMinimum: 0,
        },
        reset: {
          description:
            "An RFC 3339 date-time with `Z` or a numeric offset at which one of the account's windows opens, from 0001-01-01T00:00:00.000Z to 9999-12-31T23:59:59.999Z once its offset is applied.",
          type: "string",
          format: "date-time",
        },
        every: {
          description: "The length of a window, in exactly one unit.",
          type: "object",
          additionalProperties: false,
          minProperties: 1,
          maxProperties: 1,
          properties: {
            hours: {
              type: "integer",
              minimum: 1,
              maximum: 87600,
            },
            days: {
              type: "integer",
              minimum: 1,
              maximum: 3650,
            },
            months: {
              type: "integer",
              minimum: 1,
              maximum: 120,
            },
          },
        },
      },
    },
    usage: {
      type: "object",
      additionalProperties: false,
      required: ["environment", "provider"],
      properties: {
        environment: {
          $ref: "https://manifold.wyrd.company/schemas/service-configuration#/$defs/declared-name",
        },
        provider: {
          $ref: "https://manifold.wyrd.company/schemas/usage-record#/$defs/provider",
        },
        instance: {
          description: "The id of a T3 Code provider instance on the environment.",
          type: "string",
          minLength: 1,
        },
      },
    },
  },
};

export const priceTableSchema = {
  $schema: "https://json-schema.org/draft/2020-12/schema",
  $id: "https://manifold.wyrd.company/schemas/price-table",
  title: "Price table",
  description:
    "The prices of model tokens in one unit: the document in `prices.yml` at the root of the process repository, and the bundled price table. An empty document declares no prices.",
  type: "object",
  additionalProperties: false,
  properties: {
    unit: {
      description: "The unit of every price in the table.",
      type: "string",
      enum: ["usd"],
    },
    models: {
      description: "Price entries, keyed by model id.",
      type: "object",
      propertyNames: {
        minLength: 1,
      },
      additionalProperties: {
        $ref: "#/$defs/entry",
      },
    },
  },
  dependentRequired: {
    models: ["unit"],
  },
  $defs: {
    price: {
      description: "A non-negative decimal.",
      type: "number",
      minimum: 0,
    },
    prices: {
      type: "object",
      additionalProperties: false,
      required: ["input", "output"],
      properties: {
        input: {
          description: "Per million input tokens.",
          $ref: "#/$defs/price",
        },
        output: {
          description: "Per million output tokens.",
          $ref: "#/$defs/price",
        },
        cacheRead: {
          description: "Per million cache-read tokens.",
          $ref: "#/$defs/price",
        },
        cacheWrite: {
          description: "Per million cache-write tokens of the default lifetime.",
          $ref: "#/$defs/price",
        },
        cacheWriteOneHour: {
          description: "Per million cache-write tokens with a one-hour lifetime.",
          $ref: "#/$defs/price",
        },
        reasoning: {
          description: "Per million reasoning tokens; the output price when absent.",
          $ref: "#/$defs/price",
        },
        webSearchRequest: {
          description: "Per web search request.",
          $ref: "#/$defs/price",
        },
      },
    },
    entry: {
      type: "object",
      additionalProperties: false,
      required: ["standard"],
      properties: {
        aliases: {
          type: "array",
          uniqueItems: true,
          items: {
            type: "string",
            minLength: 1,
          },
        },
        standard: {
          $ref: "#/$defs/prices",
        },
        fast: {
          $ref: "#/$defs/prices",
        },
      },
    },
  },
};
